accounts/urls.py
from django.conf.urls import url

from django.contrib.auth import views as django_views

from . import views

urlpatterns = [
    url(r'^registration/$', views.registration_page, name='registration'),
    url(r'^activation/(?P<token>[\w]+)/$', views.activation_view, name='activation'),
    url(r'^password-reset-link/(?P<token>[\w]+)/$', views.activation_view, name='password_reset_link'),
    url(r'^profile/$', views.profile_view, name='profile'),
    url(r'^login/$', django_views.login, name='login'),
    url(r'^logout/$', django_views.logout, name='logout'),
    url(r'^restore/$', views.restore_password, name='restore_password'),
    url(r'^restore-send-email/$', views.restore_send_email, name='restore_send_email'),
    # url(r'^password-reset-link/(?P<token>[\w]+)/$', views.password_reset_link, name='password_reset_link'),
    url(r'^restore-send-sms/$', views.restore_send_sms, name='restore_send_sms'),
    url(r'^password_confirm_code/$', views.password_confirm_code, name='password_confirm_code'),
    # url(r'^password-reset-email/done/$', django_views.password_reset_done, name='password_reset_done'),
    url(r'^logout-then-login/$', django_views.logout_then_login, name='logout_then_login'),
    url(r'^reset-password/$', views.reset_password, name='reset_password'),
    url(r'^add-subscriber/$', views.add_subscriber, name='add_subscriber'),
    url(r'^upload-image/$', views.upload_image, name='upload_image'),
    url(r'^add-review/$', views.add_review, name='add_review'),
    url(r'^show-subscriptions/$', views.show_subscriptions, name='show_subscriptions'),
    url(r'^user-search/$', views.user_search, name='user_search'),
    url(r'^snap-card/$', views.snap_card, name='snap_card')
]

cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^add-to-cart/$', views.add_to_cart, name='add_to_cart'),
    url(r'^cart-detail/$', views.cart_detail, name='cart_detail'),
    url(r'^remove-from-cart/$', views.remove_from_cart, name='remove_from_cart'),
    url(r'^showcase-detail/$', views.show_showcase, name='showcase_detail'),
]

goods/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^search/$', views.search_view, name='search'),
    url(r'^modal/(?P<good_pk>\d+)/$', views.goods_modal, name='goods_modal'),
    url(r'^good/(?P<good_pk>\d+)/$', views.good_view, name='good_view'),
    url(r'^add-to-wishlist/$', views.add_to_wishlist, name='add_to_wishlist'),
    url(r'^add-user-like/$', views.add_user_like, name='add_user_like'),
    url(r'^goods-filter/$',views.goods_filter, name='goods_filter'),
    url(r'^add-new-tag/$', views.add_new_tag, name='add_new_tag'),
    url(r'^add/$', views.add_good, name='add_good'),
    url(r'^edit/(?P<good_pk>\d+)/$', views.edit_good, name='edit_good'),
    url(r'^delete/(?P<pk>\d+)/$', views.GoodDeleteView.as_view(), name='delete_good'),
    url(r'^upload-good-photo/$', views.upload_good_photo, name='upload_good_photo'),
    url(r'^delete-good-photo/$', views.delete_photo, name='delete_good_photo'),
    url(r'^wishlist/$', views.show_wishlist, name='show_wishlist'),
    url(r'^add-bid/$', views.add_auction_bid, name='add_bid'),
    url(r'^remove-bid/$', views.reject_auction_bid, name='reject_bid'),
    url(r'^disable-good/$', views.set_inactive_good, name='disable-good'),
    url(r'^accept-bid/$', views.accept_bid, name='accept-bid')
]

storesb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from filebrowser.sites import site

from storesb.settings import MEDIA_ROOT, MEDIA_URL

from main.views import index_view
from accounts.views import user_page, cropit


urlpatterns = [
    url(r'^$', index_view, name='index'),
    url(r'^main/', include('main.urls', namespace='main', app_name='main')),
    url(r'^goods/', include('goods.urls', namespace='goods', app_name='goods')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts', app_name='accounts')),
    url(r'^complaints/', include('complaints.urls', namespace='complaints', app_name='complaints')),
    url(r'^chat/', include('chat.urls', namespace='chat', app_name='chat')),
    url(r'^cart/', include('cart.urls', namespace='cart', app_name='cart')),
    url('^pages/', include('pages.urls', namespace='pages', app_name='pages')),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'social-auth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^(?P<user_slug>\w+)/$', user_page, name='user_page'),
    url(r'^cropit$', cropit, name='cropit'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from taggit.models import Tag

from main.models import BaseModel
from main.countries_list import COUNTRIES
from goods.models import Good

from .constants import LIME, ORANGE, NOT_DEFINED, PRIVATE_PERSON, LEGAL_ENTITY, MALE, FEMALE, VK, FACEBOOK, PINTEREST
from .constants import TWITTER, ODNOKLASSNIKI

# Create your models here.


class SocialNetwork(BaseModel):
    """
    SocialNetwork model. Store access tokens and name of soc. networks.
    """
    NETWORKS = (
        (VK, "VK"),
        (FACEBOOK, "Facebook"),
        (PINTEREST, "Pinterest"),
        (TWITTER, "Twitter"),
        (ODNOKLASSNIKI, "Odnoklassniki")
    )
    title = models.CharField(max_length=100, verbose_name=_("Title"))
    network_id = models.CharField(choices=NETWORKS, verbose_name=_('Network ID'), unique=True, null=True, blank=True,
                                  max_length=20)

    def __str__(self):
        return self.title
#
#
# class SocialAccount(BaseModel):
#     """
#     User social accounts. Store link to user social network page and setting to post on his page.
#     """
#     user = models.OneToOneField(User, related_name="social_account")
#     social_network = models.ForeignKey(SocialNetwork, verbose_name=_("Social network"))
#     account_link = models.CharField(max_length=255, null=True, blank=True, verbose_name=_("Account link"))
#     auto_post_updated = models.BooleanField(default=False, verbose_name=_("Auto post"))
#
#     def __str__(self):
#         return self.user.username


class UserProfile(BaseModel):
    """
    User profile.
    """
    ORG_FORM = (
        (PRIVATE_PERSON, _("Private person")),
        (LEGAL_ENTITY, _("Legal entity")),
        # (2, _("Individual entrepreneur"))
    )
    SEX = (
        (MALE, _('MALE')),
        (FEMALE, _('FEMALE')),
        (NOT_DEFINED, _('NOT DEFINED'))
    )
    USER_THEME = (
        (LIME, _("LIME")),
        (ORANGE, _("ORANGE")),
        (NOT_DEFINED, _("NOT DEFINED"))
    )
    STATUS = (
        (0, _("Offline")),
        (1, _("Online"))
    )

    user = models.OneToOneField(User, related_name="profile")
    avatar = models.ImageField(upload_to='avatars', blank=True, null=True, verbose_name=_("Avatar"))
    cover = models.ImageField(upload_to='covers', blank=True, null=True, verbose_name=_("Cover"))
    description = models.TextField(null=True, blank=True, verbose_name=_("About"))
    sex = models.IntegerField(choices=SEX, default=2, verbose_name=_("SEX"))
    org_form = models.IntegerField(choices=ORG_FORM, default=0, verbose_name=_("Form of incorporation"))
    country = models.CharField(max_length=3, verbose_name=_("Country"), choices=COUNTRIES, default='RU')
    city = models.CharField(max_length=255, null=True, blank=True, verbose_name=_("City"))
    phone = models.CharField(verbose_name=_("Phone"), null=True, blank=True, max_length=20)
    additional_phone = models.CharField(verbose_name=_("Additional phone"), null=True, blank=True, max_length=20)
    skype = models.CharField(max_length=255, null=True, blank=True, verbose_name="Skype")
    instagram = models.CharField(max_length=255, null=True, blank=True, verbose_name="Instagram")
    site = models.CharField(verbose_name="Web site", null=True, blank=True, max_length=128)
    map_link = models.TextField(verbose_name=_("Google map link"), null=True, blank=True)
    slug = models.SlugField(max_length=255, verbose_name=_("Profile link"), unique=True)
    theme = models.IntegerField(choices=USER_THEME, default=2, verbose_name=_("Theme"))
    status = models.IntegerField(choices=STATUS, default=1, verbose_name=_("User online status"))
    auto_post_to_networks = models.ManyToManyField(SocialNetwork, verbose_name=_('Allow auto post to'))

    def avatar_tag(self):
        return u'<img src="%s" height=75 width=75 />' % (self.avatar.url)

    avatar_tag.short_description = _("Current avatar")
    avatar_tag.allow_tags = True

    def __str__(self):
        return self.user.username

    def get_all_about_marks(self):
        marks = Reviews.objects.filter(about_user=self.user).values_list('mark', flat=True)
        return marks

    def get_my_marks(self):
        marks = Reviews.objects.filter(author=self.user).values_list('mark', flat=True)
        return marks

    def get_absolute_url(self):
        return reverse('user_page', args=[self.slug])

    def get_mark_count_about(self, mark):
        marks_count = Reviews.objects.filter(about_user=self.user).filter(mark=mark).count()
        return marks_count

    def get_about_average_mark(self):
        marks = self.get_all_about_marks()
        avg = 0
        sum = 0
        if len(marks) > 0:
            for mark in marks:
                sum += mark
            avg = sum / len(marks)
        return avg

    def get_total_about_marks(self):
        marks_count = Reviews.objects.filter(about_user=self.user).count()
        return marks_count

    def get_lots_count(self):
        lots_count = self.user.goods.count()
        return lots_count

    def get_subscribers_count(self):
        count_lists = Subscribers.objects.filter(users=self.user).count()
        return count_lists

    def get_subscription_count(self):
        my_list = Subscribers.objects.get(owner=self.user)
        count = my_list.users.count()
        return count

    def get_user_tags(self):
        """
        Get all user tags
        :return:
        """
        goods = Good.objects.filter(user=self.user)
        tags = Tag.objects.filter(good__in=goods).distinct()
        return tags

    class Meta:
        ordering = ('updated',)


class ActivationProfile(models.Model):
    """
    Model to store email token or sms code for registration.
    """
    user = models.ForeignKey(User)
    token = models.CharField(max_length=255)
    sms_key = models.CharField(max_length=10)
    valid_through = models.DateTimeField()
    password_reset = models.BooleanField(default=False)


class UserComments(BaseModel):
    """

    """
    about_user = models.ForeignKey(User, related_name='about_comments')
    user = models.ForeignKey(User, related_name='users_comments')
    text = models.TextField(verbose_name=_('Comment'))

    def __str__(self):
        return self.about_user.title

    class Meta:
        ordering = ('created',)


class Subscribers(BaseModel):
    """

    """
    owner = models.OneToOneField(User, related_name='subscribers')
    users = models.ManyToManyField(User, related_name='subscriptions')

    def __str__(self):
        return self.owner.username

    class Meta:
        ordering = ('created',)


class Reviews(BaseModel):
    """

    """
    MARKS = (
        (0, 0),
        (0.5, 0.5),
        (1, 1),
        (1.5, 1.5),
        (2, 2),
        (2.5, 2.5),
        (3, 3),
        (3.5, 3.5),
        (4, 4),
        (4.5, 4.5),
        (5, 5)
    )
    about_user = models.ForeignKey(User, related_name='reviews')
    author = models.ForeignKey(User, related_name='my_reviews')
    text = models.TextField(verbose_name=_('Text'))
    mark = models.DecimalField(choices=MARKS, default=0, max_digits=3, decimal_places=1)

    def __str__(self):
        return self.about_user.username + ' ' + str(self.mark)

    class Meta:
        ordering = ('created',)


class CardData(BaseModel):
    user = models.ForeignKey(User, related_name='cards', verbose_name=_('User'))
    number = models.BigIntegerField(verbose_name=_('Card number'))
    valid_throgh_month = models.IntegerField(verbose_name=_('Month'))
    valid_throgh_year = models.IntegerField(verbose_name=_('Year'))

    def __str__(self):
        return self.user.username + ' ' + 'card'

    class Meta:
        ordering = ('updated', )

goods/forms.py
from django import forms
from .models import Good, GoodsProperties
from django.utils.translation import ugettext_lazy as _


class GoodForm(forms.ModelForm):
    """
    Good form
    """
    quantity = forms.CharField(required=False)
    old_price = forms.CharField(required=False)
    new_price = forms.CharField(required=False)
    price = forms.CharField(required=False)
    # min_price = forms.CharField(required=False)
    # reserve_price = forms.CharField(required=False)
    # max_price = forms.CharField(required=False)

    class Meta:
        model = Good
        exclude = ('user', 'is_active', 'users_like', )


class CustomImageUpload(forms.Form):
    """
    Upload images form. Used in add_goods template and view
    """
    image1 = forms.CharField(required=False, widget=forms.HiddenInput())
    image2 = forms.CharField(required=False, widget=forms.HiddenInput())
    image3 = forms.CharField(required=False, widget=forms.HiddenInput())
    image4 = forms.CharField(required=False, widget=forms.HiddenInput())
    image5 = forms.CharField(required=False, widget=forms.HiddenInput())


class GoodPropetiesForm(forms.ModelForm):
    """
    Good properties form
    """
    class Meta:
        model = GoodsProperties
        exclude = ('good',)

goods/templates/delete_confirmation.html
{% extends 'chat_base.html' %}
{% load i18n %}
{% block content %}
    <div class="custom-caption">
        <form action="" method="post" style="margin-left: 37%">
            {% csrf_token %}
            {% trans 'Are you sure you want to delete' %} "{{ object.title }}"?
            <br>
            <input type="submit" value="{% trans 'Delete' %}" class="mybtn mybtn-small" style="margin-left: 9%">
        </form>
    </div>
{% endblock %}

goods/templates/good_ajax.html
{% load main_tags %}
{% load goods_tags %}
{% load thumbnail %}
{% load i18n %}

{% for good_same in goods %}

    <div class="ui card">
        <a class="image" href="{% url 'goods:good_view' good_same.pk %}">
            {% show_good_image good_same %}
        </a>
        <div class="content">
            <a href="{{ good_same.user.profile.site|check_http_prefix }}" id="site-min">
                {{ good_same.user.profile.site }}
            </a>
            <div class="rev-min">{{ good_same.title }}</div>
            <div class="place-min">
                <i class="marker icon"></i>
                <a href="{% url 'goods:search' %}?filter=1&location={{ good_same.user.profile.get_country_display }}">{{ good_same.user.profile.get_country_display }}</a>,
                <a href="{% url 'goods:search' %}?filter=1&location={{ good_same.user.profile.get_country_display }}">{{ good_same.user.profile.city }}</a>
            </div>
        </div>
        <div class="content">
            {% for tag in good_same.tags.all %}
                <a href="{% url 'goods:search' %}?filter=1&tag_id[]={{ tag.id }}" class="ui grey small label">{{ tag.name }}</a>
            {% empty %}
                Good without tags
            {% endfor %}
{#							<ul id="modal-statistics">#}
{#								<li>50</li>#}
{#								<li>50</li>#}
{#								<li>50</li>#}
{#								<li>50</li>#}
{#								<li>50</li>#}
{#								<div class="clear"></div>#}
{#							</ul>#}
        </div>
        <div class="content">
            <img class="ui avatar image left floated meta" src="{{ good_same.user.profile.avatar.url }}">
            <a class="user_link" href="{{ good_same.user.profile.get_absolute_url }}">{{ good_same.user.username }}</a><br>
            <span class="user_status">{{ good_same.user.profile.get_status_display }}</span>
            <div class="right floated meta header price-min">{{ good_same.get_good_price_by_deal }}</div>
        </div>
</div>

{% endfor %}

goods/templates/good_image.html
{% load staticfiles %}
{% load thumbnail %}
{% if good.get_first_image %}
<img src="/media/{{ good.get_first_image.image }}" alt="{{ good.title }}" {% if css_class %}class="{{ css_class }}"{% endif %}>
{% else %}
<img src="{% static 'images/no-good-image.png' %}" width="{{ width }}px" height="{{ height }}px" alt="{{ good.title }}" {% if css_class %}class="{{ css_class }}"{% endif %}>
{% endif %}

goods/templates/search_category_ajax.html
{% load staticfiles %}
{% load thumbnail %}
{% load i18n %}
{% load main_tags %}
        {% if objects_count > 0 and objects_count <= 3 and objects.number == 1 %}
            {% include "search_sellers.html" %}
        {% endif %}
        {% for object in objects %}
            {% if objects_count > 3 and forloop.counter0 == 2 and objects.number == 1 %}
                {% include "search_sellers.html" %}
            {% endif %}
            <div class="ui card" data-deal-filter='{{ object.deal }}' class="{% if object.deal == AUCTION %}auction{% elif object.deal == SALE %}sale{% endif %} deal">
                <a rel="example_group" class="image fancybox fancybox.iframe" href="{% url 'goods:goods_modal' object.pk %}">
                    {% if object.get_first_image %}
                        <img src="{{ object.get_first_image.image.url }}">
                    {% else %}
                        <img src="{% static 'images/no-good-image.png' %}">
                    {% endif %}
                </a>
                <div class="additional-stats show content">
                    <a href="{{ object.user.profile.site|check_http_prefix }}" id="site-min">
                        {{ object.user.profile.site }}
                    </a>
                    <div class="rev-min">
                        {{ object.title }}
                    </div>
                    <div class="place-min">
                        <a href="{% url 'goods:search' %}?filter=1&location={{ object.user.profile.get_country_display }}">{{ object.user.profile.get_country_display }}</a>
                        <a href="{% url 'goods:search' %}?filter=1&location={{ object.user.profile.city}}">{{ object.user.profile.city }}</a>
                    </div>
                </div>
                <div class="content">
                    <div id="tags-min-block">
                        {% for tag in object.tags.all %}
                            <a href="#" class="ui small olive label">{{ tag.name }}</a>
                        {% empty %}
                            Good without tags
                        {% endfor %}
                    </div>
                </div>
                <!--<div class="content">
                        <ul id="modal-statistics">
                            <li>50</li>
                            <li>50</li>
                            <li>50</li>
                            <li>50</li>
                            <li>50</li>
                            <div class="clear"></div>
                        </ul>
                </div>-->
                <div class="content">
                <a class="ui left floated meta icon-min" href="{{ object.user.profile.get_absolute_url }}">
                    <img src="{{ object.user.profile.avatar.url }}">
                </a>
                <a class="user_link" href="{{ object.user.profile.get_absolute_url }}">{{ object.user.username }}</a><br>
                <span class="user_status">{{ object.user.profile.get_status_display }}</span>
                <div class="right floated meta header price-min">
                    {% if object.deal == SALE %}
                        {{ object.new_price }}
                        {% trans 'new price' %}
                        {{ object.old_price }} $
                        {% trans 'old price' %}
                    {% elif object.deal == BUY_SELL %}
                        {{ object.price }}
                    {% else %}
                        {{ object.reserve_price }}
                        {{ object.bids.count }} {% trans 'bids' %}
                        {{ object.max_price }} $
                        {% trans 'fix price' %}
                    {% endif %}
                </div>
                <!--<div class="hidden-price-panel">
                    <button class="pay">{% trans 'Pay' %}</button>
                </div>
                {% if object.deal == SALE %}
                    <div class="discount">{{ object.get_sale_percent }} %</div>
                {% elif object.deal == AUCTION %}
                    <div class="counter"> 10 | 05 | 25</div>
                {% endif %}
                <div class="cross-goods">
                    <img src="{% static 'images/categories/cross-little-icon.png' %}">
                </div>-->
                </div>
            </div>
        {% empty %}
            <div class="sixteen wide center aligned column">
            <h2>
                <p class="sum-text">{% trans 'No results found' %}</p>
            </h2>
            </div>
        {% endfor %}

goods/templates/search_sellers.html
{% load thumbnail %}
{% load i18n %}
<div id="sellers" class="ui card">
    <div class="content">
        <div class="headSeller">
            {% trans 'Sellers in this category' %}
        </div>
    </div>
    <div class="content">
        <ul>
        {% for seller in sellers %}
            <li class="clearfix">
                <a class="image" href="{{ seller.get_absolute_url }}">
                    <img src="/media/{{ seller.avatar }}">
                </a>
                <a class="user_link" href="{{ seller.get_absolute_url }}">{{ seller.user.username }}</a>
            </li>
        {% endfor %}
        </ul>
    </div>
    <div class="content more">
        <a class="more_link" href="{% url 'accounts:user_search' %}">{% trans 'More' %}</a>
    </div>
</div>