accounts/urls.py
from django.conf.urls import url

from django.contrib.auth import views as django_views

from . import views

urlpatterns = [
    url(r'^registration/$', views.registration_page, name='registration'),
    url(r'^activation/(?P<token>[\w]+)/$', views.activation_view, name='activation'),
    url(r'^password-reset-link/(?P<token>[\w]+)/$', views.activation_view, name='password_reset_link'),
    url(r'^profile/$', views.profile_view, name='profile'),
    url(r'^login/$', django_views.login, name='login'),
    url(r'^logout/$', django_views.logout, name='logout'),
    url(r'^restore/$', views.restore_password, name='restore_password'),
    url(r'^restore-send-email/$', views.restore_send_email, name='restore_send_email'),
    # url(r'^password-reset-link/(?P<token>[\w]+)/$', views.password_reset_link, name='password_reset_link'),
    url(r'^restore-send-sms/$', views.restore_send_sms, name='restore_send_sms'),
    url(r'^password_confirm_code/$', views.password_confirm_code, name='password_confirm_code'),
    # url(r'^password-reset-email/done/$', django_views.password_reset_done, name='password_reset_done'),
    url(r'^logout-then-login/$', django_views.logout_then_login, name='logout_then_login'),
    url(r'^reset-password/$', views.reset_password, name='reset_password'),
    url(r'^add-subscriber/$', views.add_subscriber, name='add_subscriber'),
    url(r'^upload-image/$', views.upload_image, name='upload_image'),
    url(r'^add-review/$', views.add_review, name='add_review'),
    url(r'^show-subscriptions/$', views.show_subscriptions, name='show_subscriptions'),
    url(r'^user-search/$', views.user_search, name='user_search'),
    url(r'^snap-card/$', views.snap_card, name='snap_card')
]

cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^add-to-cart/$', views.add_to_cart, name='add_to_cart'),
    url(r'^cart-detail/$', views.cart_detail, name='cart_detail'),
    url(r'^remove-from-cart/$', views.remove_from_cart, name='remove_from_cart'),
    url(r'^showcase-detail/$', views.show_showcase, name='showcase_detail'),
]

chat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^thread-list/$', views.show_threads_list, name='show_thread_list'),
    url(r'^send-message/$', views.send_message, name='send_message'),
    url(r'^thread/(?P<thread_id>\d+)/$', views.show_thread, name='show_thread'),
    url(r'^send_message_api/$', views.send_message_api, name='send_message_api'),
    url(r'^check_username/$', views.check_username, name='check_username'),
    url(r'^send_message_ajax/$', views.send_message_ajax, name='send_message_ajax'),
]

goods/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^search/$', views.search_view, name='search'),
    url(r'^modal/(?P<good_pk>\d+)/$', views.goods_modal, name='goods_modal'),
    url(r'^good/(?P<good_pk>\d+)/$', views.good_view, name='good_view'),
    url(r'^add-to-wishlist/$', views.add_to_wishlist, name='add_to_wishlist'),
    url(r'^add-user-like/$', views.add_user_like, name='add_user_like'),
    url(r'^goods-filter/$',views.goods_filter, name='goods_filter'),
    url(r'^add-new-tag/$', views.add_new_tag, name='add_new_tag'),
    url(r'^add/$', views.add_good, name='add_good'),
    url(r'^edit/(?P<good_pk>\d+)/$', views.edit_good, name='edit_good'),
    url(r'^delete/(?P<pk>\d+)/$', views.GoodDeleteView.as_view(), name='delete_good'),
    url(r'^upload-good-photo/$', views.upload_good_photo, name='upload_good_photo'),
    url(r'^delete-good-photo/$', views.delete_photo, name='delete_good_photo'),
    url(r'^wishlist/$', views.show_wishlist, name='show_wishlist'),
    url(r'^add-bid/$', views.add_auction_bid, name='add_bid'),
    url(r'^remove-bid/$', views.reject_auction_bid, name='reject_bid'),
    url(r'^disable-good/$', views.set_inactive_good, name='disable-good'),
    url(r'^accept-bid/$', views.accept_bid, name='accept-bid')
]

main/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^calculator/$', views.calculator_view, name='calculator'),
]

storesb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from filebrowser.sites import site

from storesb.settings import MEDIA_ROOT, MEDIA_URL

from main.views import index_view
from accounts.views import user_page, cropit


urlpatterns = [
    url(r'^$', index_view, name='index'),
    url(r'^main/', include('main.urls', namespace='main', app_name='main')),
    url(r'^goods/', include('goods.urls', namespace='goods', app_name='goods')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts', app_name='accounts')),
    url(r'^complaints/', include('complaints.urls', namespace='complaints', app_name='complaints')),
    url(r'^chat/', include('chat.urls', namespace='chat', app_name='chat')),
    url(r'^cart/', include('cart.urls', namespace='cart', app_name='cart')),
    url('^pages/', include('pages.urls', namespace='pages', app_name='pages')),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'social-auth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^(?P<user_slug>\w+)/$', user_page, name='user_page'),
    url(r'^cropit$', cropit, name='cropit'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

chat/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from django.utils.translation import ugettext_lazy as _


# Create your models here.


class Thread(models.Model):
    """
    Thread model. Contains all users in chat.
    """
    participants = models.ManyToManyField(User, verbose_name=_("Users"), related_name='threads')
    last_message = models.DateTimeField(null=True, blank=True, db_index=True)
    has_unread = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('chat:show_thread', args=[self.id])

    def get_message_count(self):
        return Message.objects.filter(thread=self).count()

    def __str__(self):
        return str(self.pk)

    class Meta:
        ordering = ('-last_message',)


class Message(models.Model):
    """
    Message model.
    """
    sender = models.ForeignKey(User, verbose_name=_("Sender"), related_name='my_messages')
    thread = models.ForeignKey(Thread, verbose_name=_("Thread"), related_name='messages')
    text = models.TextField(verbose_name=_("Message"))
    datetime = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name=_("Date and time"))


def update_last_message_datetime(sender, instance, created, **kwargs):
    """
    Update Thread's last_message field when new message sent
    """
    if not created:
        return
    Thread.objects.filter(id=instance.thread.id).update(last_message=instance.datetime, has_unread=True)


post_save.connect(update_last_message_datetime, sender=Message)

chat/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.contrib import messages
from django.utils.translation import ugettext as _
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.conf import settings

from common.decorators import ajax_required
from main.forms import SearchForm
from .models import Thread, Message
from .functions import check_user_in_blocklist, send_message_helper

# Create your views here.


@login_required
def show_threads_list(request):
    """
    Show thread list
    :param request:
    :return:
    """
    threads = Thread.objects.filter(participants=request.user)
    if threads:
        for thread in threads:
            try:
                thread.partner = thread.participants.exclude(id=request.user.id)[0]
            except IndexError:
                thread.partner = None
    form = SearchForm()
    return render(request, 'threads_list.html', {'threads': threads, 'user': request.user, 'form': form})


@login_required
@require_POST
def send_message(request):
    """
    Send message through form
    :param request:
    :return:
    """
    sender = request.user
    try:
        partner = User.objects.get(username=request.POST['partner'])
    except (User.DoesNotExist, User.MultipleObjectsReturned):
        messages.error(request, _("Your partner doesn't exist or error in username"))
        return render(request, 'error.html')
    if sender == partner:
        messages.error(request, _("You can't send messages to yourself"))
        return render(request, 'error.html')
    # Check that sender is not in block list
    if check_user_in_blocklist(sender, partner):
        messages.error(request, _("Your partner blocked messages from you"))
        return render(request, 'error.html')
    threads = Thread.objects.filter(participants=partner).filter(participants=sender)
    if threads.exists():
        thread = threads[0]
    else:
        thread = Thread()
        thread.save()
        thread.participants.add(sender, partner)
    send_message_helper(thread, request.POST.get('text'), sender)
    return redirect(reverse('chat:show_thread', args=[thread.id]))


@login_required
def show_thread(request, thread_id):
    """
    Show messages thread
    :param request: HttpRequest
    :param thread_id: Thread id
    :return:
    """
    thread = get_object_or_404(Thread, id=thread_id)
    thread.has_unread = False
    thread.save()
    messages = Message.objects.filter(thread=thread).order_by("datetime")
    try:
        partner = thread.participants.exclude(id=request.user.id)[0]
    except IndexError:
        partner = None
    form = SearchForm()
    return render(request, 'thread.html', {'thread': thread, 'messages': messages, 'partner': partner,
                                           'user': request.user, 'form': form})


@csrf_exempt
@require_POST
def send_message_api(request):
    """
    Accept messages from tornado app
    :param request: Retirn JsonResponse
    :return:
    """
    if request.POST['API_KEY'] == settings.MESSAGE_API_KEY:
        try:
            thread = Thread.objects.get(id=request.POST['thread'])
        except (Thread.DoesNotExist, Thread.MultipleObjectsReturned):
            return JsonResponse({'Error': 'Invalid thread id'})
        try:
            sender = User.objects.get(id=request.POST['sender_id'])
        except (User.DoesNotExist, User.MultipleObjectsReturned):
            return JsonResponse({'Error': 'Invalid user id', 'thread': thread.id})
        text = request.POST.get('text')
        recipients = thread.participants.exclude(id=sender.id)
        for patner in recipients:
            if check_user_in_blocklist(sender, patner):
                return JsonResponse({'Error': 'Sender in blocklist', 'thread': thread.id})
        message = send_message_helper(thread, text, sender)
        return JsonResponse({'status': 'ok', 'datetime': message.datetime.strftime('%Y-%m-%d %H:%M:%S'),
                             'sender': message.sender.username, 'sender_id': message.sender.id,
                             'text': message.text, 'thread': message.thread.id})
    else:
        return JsonResponse({'Error': 'Invalid API key'})


@require_POST
@ajax_required
def check_username(request):
    """
    Check if users with this symbols exists. If true return first username. Else return error and empty result.
    Call by AJAX check_username script.
    :param request: HttpRequest (Post with 'parther' parameter)
    :return: Json response
    """
    users = User.objects.filter(username__icontains=request.POST.get('partner'))
    if users.count() != 0:
        return JsonResponse({'status': 'ok', 'result': users[0].username})
    else:
        return JsonResponse({'status': 'error', 'result': ''})


@require_POST
@login_required
@ajax_required
def send_message_ajax(request):
    """
    Send message method, which called by AJAX.
    :param request: HttpRequest (AJAX)
    :return: HttpResponse as JSON
    """
    sender = request.user
    try:
        partner = User.objects.get(pk=request.POST['partner'])
    except User.DoesNotExist:
        return JsonResponse({'status': 'error', 'reason': 'User not found'})
    if sender == partner:
        return JsonResponse({'status': 'error', 'reason': 'Recipient cannot be yourself'})
    # Check that sender is not in block list
    if check_user_in_blocklist(sender, partner):
        return JsonResponse({"status": "error", 'reason': 'You blocked'})
    threads = Thread.objects.filter(participants=partner).filter(participants=sender)
    if threads.exists():
        thread = threads[0]
    else:
        thread = Thread()
        thread.save()
        thread.participants.add(sender, partner)
    send_message_helper(thread, request.POST.get('text'), sender)
    return JsonResponse({'status': 'ok'})

chat/templates/chat_base.html
{% load staticfiles %}
{% load main_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block scripts %}
        <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
        <script src="{% static 'js/jquery-ui.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/npm.js' %}"></script>
        <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'css/chat.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main_styles.css' %}">
        <script src="{% static 'js/jquery.cookie.js' %}"></script>
        <script>
            $(document).ready(function () {
                var csrftoken = $.cookie('csrftoken');
                function csrfSafeMethod (method) {
                    // These HTTP methods do not require CSRF protection
                    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                }
                $.ajaxSetup({
                    beforeSend: function (xhr, settings) {
                        if(!csrfSafeMethod(settings.type) && !this.crossDomain) {
                            // Set X-CSRFToken HTTP Header
                            xhr.setRequestHeader("X-CSRFToken", csrftoken);
                        }
                    }
                });
            });
        </script>
    {% endblock %}
</head>
<body>
    <div id="wrapper" class="green">
        <header class="black blackheader">
            {% if request.user.is_authenticated %}
                <ul>
                    <li>
                        <div class="search-modal"></div>
                    </li>
                    <li>
                        <a href="{% url 'accounts:show_subscriptions' %}"></a>
                        {{ request.user|show_count_subscriptions|safe }}
                    </li>
                    <li>
                        <a href="#"></a>
                        <span>258</span>
                    </li>
                    <li>
                        <a href="{% url 'chat:show_thread_list' %}"></a>
                        {{ request.user|show_unread_message_count|safe }}
                    </li>
                    <li>
                        <a href="{% url 'goods:show_wishlist' %}"></a>
                        {{ request.user|show_count_goods_in_wishlist|safe }}
                    </li>
                    <li>
                        <a href="{{ request.user.profile.get_absolute_url }}"></a>
                    </li>
                    <li>
                        <a href="{% url 'main:calculator' %}"></a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:user_search' %}"></a>
                    </li>
                    <li>
                        <a href="#"></a>
                        <span>258</span>
                    </li>
                    <li>
                        <a href="{% url 'accounts:profile' %}"></a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:logout' %}">
                            <div></div>
                        </a>
                    </li>
                </ul>
            {% else %}
                {% include 'sign_in.html' %}
            {% endif %}
		    <div class="clear"></div>
	    </header>
        <div class="search-box">
			<img class="img-search" src="{% static 'images/search-green-icon_03.png' %}">
            <form action="{% url 'goods:search' %}" method="get">
                {{ form.query|add_class_to_formfield:"search" }}
            </form>
		</div>
		<div class="clear"></div>
        {% block content %}
        {% endblock %}
    </div>
    <footer>
	    {% include 'social_links.html' %}
    </footer>
    <script>
        $('.search-modal').click(function (){
		    $('.search-box').show();
		    $(this).parents('header').hide();
	    });
	    $('.img-search').click(function (){
		    $(this).parent().hide();
		    $('.blackheader').show();
	    });
	    $('input[class="search"]').keypress(function (e) {
	        var key = e.which;
	        if(key == 13)  // the enter key code
	        {
	            $(this).parent().hide();
	            $('.blackheader').show();
	        }
	    });
    </script>
</body>
</html>

chat/templates/thread.html
{% extends 'chat_base.html' %}
{% load staticfiles %}
{% load i18n %}
{% block title %}{% blocktrans %}Chat with{% endblocktrans %} {{ partner }}{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script src="{% static 'js/chat.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="container main-container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="conversation border-green">
                    {% for message in messages %}
                        {% if message.sender == user %}
                            <div class="sender-bubble">
                                <p class="sender">
                                    <span class="message_date">{{ message.datetime|date:'j-m-Y H:i' }}</span> {{ message.sender }}:
                                </p>
                        {% else %}
                            <div class="partner-bubble">
                                <p class="receiver">
                                    <span class="message_date">{{ message.datetime|date:'j-m-Y H:i' }}</span> {{ message.sender }}:
                                </p>

                        {% endif %}
                            <p class="chat_message">
                                {{ message.text }}
                            </p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 text-right username_block">
                <h2 class="users">
                    <span class="chat_username">{{ user.username }}</span>
                    {% if user.profile.avatar != None %}
                        <img src="{{ user.profile.avatar.url }}" class="chat_image chat_sender circular">
                    {% else %}
                        <img src="{% static 'images/no-good-image.png' %}" class="chat_image chat_sender circular">
                    {% endif %}
                </h2>
            </div>
            <div class="col-md-6 text-center col-center-block">
                <form method="post" id="idSendMessageForm">
                    {% csrf_token %}
                    <input type="hidden" name="sender" value="{{ user.id }}" id="idSender">
                    <input type="hidden" name="chat" value="{{ thread.id }}" id="idChat">
                    <textarea class="form-control" placeholder="{% trans 'Enter message' %}" id="idText"></textarea>
                    <input type="submit" value="{% trans 'Send!' %}" class="mybtn mybtn-small" id="idSend">
                </form>
            </div>
            <div class="col-md-3 text-left username_block">
                <h2 class="users">
                    {% if partner %}
                        <span class="chat_username"></span>
                        <a href="{{ partner.profile.get_absolute_url }}">
                            {{ partner.username }}
                        </a>
                        {% if partner.profile.avatar.url != None %}
                            <img src="{{ partner.profile.avatar.url }}" class="chat_image chat_receiver circular">
                        {% else %}
                            <img src="{% static 'images/no-good-image.png' %}" class="chat_image chat_receiver circular">
                        {% endif %}
                    {% else %}
                        {% trans 'No partner' %}
                    {% endif %}
                </h2>
            </div>
        </div>
    </div>
{% endblock %}

chat/templates/threads_list.html
{% extends 'chat_base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% load chat_tags %}
{% load i18n %}
    {% block title %}{{ user.username }} chat list{% endblock %}
    {% block scripts %}
        {{ block.super }}
        <script src="{% static 'js/check_username.js' %}"></script>
    {% endblock %}
{% block content %}
    <div class="container main-container">
        <div class="row">
            <div class="col-md-4 text-center">
                <h3 class="headline">
                    {% if user.profile.avatar %}
                     {% thumbnail user.profile.avatar "63x63" as avatar %}
                         <img src="{{ avatar.url }}" class="circular" alt="{{ user.username }}">
                     {% endthumbnail %}
                {% endif %}
                    <a href="{{ user.profile.get_absolute_url }}">
                        {{ user.username }}
                    </a>
                </h3>
                <button data-toggle="modal" data-target="#SendMessageModal" class="button-style">{% trans 'Write message' %}</button>
                <div class="modal fade text-left" id="SendMessageModal" tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                    &times;
                                </button>
                                <h4 class="modal-title">{% blocktrans %}Send new message{% endblocktrans %}</h4>
                            </div>
                            <div class="modal-body">
                                <div id="modal_error"></div>
                                <form action="{% url 'chat:send_message' %}" method="post" id="idSendMessageForm">
                                    {% csrf_token %}
                                    <label for="idReceiver">{% trans 'Enter username' %}</label>
                                    <div class="green" id="usernameHint"></div>
                                    <input type="text" name="partner" class="form-control" placeholder="{% trans 'Enter username' %}" id="idReceiver">
                                    <label for="messageText">{% trans 'Enter message' %}:</label>
                                    <textarea name="text" class="form-control" placeholder="{% trans 'Enter message' %}" id="messageText"></textarea>
                                    <input type="submit" value="{% trans 'Send' %}" class="mybtn mybtn-small">
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal" id="id_sendCloseButton">
                                    {% trans 'Close' %}
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <h3 class="text-center">{% blocktrans %}Your contacts{% endblocktrans %}</h3>
                <table class="table table-responsive">
                    <thead>
                        <tr>
                            <th>{% trans 'User' %}</th>
                            <th>{% trans 'Total messages' %}</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for thread in threads %}
                            <tr>
                                <td>
                                    {% if thread.partner %}
                                        {% if user|check_user_in_blocklist_tag:thread.partner %}
                                            {{ thread.partner }} add you in blocklist.
                                        {% else %}
                                            <a href="{{ thread.get_absolute_url }}">
                                                <h4>{{ thread.partner }}</h4>
                                            </a>
                                        {% endif %}
                                    {% else %}
                                        {% trans 'No partner' %}
                                    {% endif %}
                                </td>
                                <td>
                                    {{ thread.get_message_count }}
                                </td>
                                <td>
                                    {% if thread.has_new %}
                                        New message
                                    {% endif %}
                                </td>
                                <td>
                                    {% if thread.has_unread %}
                                        <span class="unread-green"> Unread message</span>
                                    {% endif %}
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="3">
                                    {% blocktrans %}You haven't contacts{% endblocktrans %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}