accounts/urls.py
from django.conf.urls import url

from django.contrib.auth import views as django_views

from . import views

urlpatterns = [
    url(r'^registration/$', views.registration_page, name='registration'),
    url(r'^activation/(?P<token>[\w]+)/$', views.activation_view, name='activation'),
    url(r'^password-reset-link/(?P<token>[\w]+)/$', views.activation_view, name='password_reset_link'),
    url(r'^profile/$', views.profile_view, name='profile'),
    url(r'^login/$', django_views.login, name='login'),
    url(r'^logout/$', django_views.logout, name='logout'),
    url(r'^restore/$', views.restore_password, name='restore_password'),
    url(r'^restore-send-email/$', views.restore_send_email, name='restore_send_email'),
    # url(r'^password-reset-link/(?P<token>[\w]+)/$', views.password_reset_link, name='password_reset_link'),
    url(r'^restore-send-sms/$', views.restore_send_sms, name='restore_send_sms'),
    url(r'^password_confirm_code/$', views.password_confirm_code, name='password_confirm_code'),
    # url(r'^password-reset-email/done/$', django_views.password_reset_done, name='password_reset_done'),
    url(r'^logout-then-login/$', django_views.logout_then_login, name='logout_then_login'),
    url(r'^reset-password/$', views.reset_password, name='reset_password'),
    url(r'^add-subscriber/$', views.add_subscriber, name='add_subscriber'),
    url(r'^upload-image/$', views.upload_image, name='upload_image'),
    url(r'^add-review/$', views.add_review, name='add_review'),
    url(r'^show-subscriptions/$', views.show_subscriptions, name='show_subscriptions'),
    url(r'^user-search/$', views.user_search, name='user_search'),
    url(r'^snap-card/$', views.snap_card, name='snap_card')
]

cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^add-to-cart/$', views.add_to_cart, name='add_to_cart'),
    url(r'^cart-detail/$', views.cart_detail, name='cart_detail'),
    url(r'^remove-from-cart/$', views.remove_from_cart, name='remove_from_cart'),
    url(r'^showcase-detail/$', views.show_showcase, name='showcase_detail'),
]

chat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^thread-list/$', views.show_threads_list, name='show_thread_list'),
    url(r'^send-message/$', views.send_message, name='send_message'),
    url(r'^thread/(?P<thread_id>\d+)/$', views.show_thread, name='show_thread'),
    url(r'^send_message_api/$', views.send_message_api, name='send_message_api'),
    url(r'^check_username/$', views.check_username, name='check_username'),
    url(r'^send_message_ajax/$', views.send_message_ajax, name='send_message_ajax'),
]

goods/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^search/$', views.search_view, name='search'),
    url(r'^modal/(?P<good_pk>\d+)/$', views.goods_modal, name='goods_modal'),
    url(r'^good/(?P<good_pk>\d+)/$', views.good_view, name='good_view'),
    url(r'^add-to-wishlist/$', views.add_to_wishlist, name='add_to_wishlist'),
    url(r'^add-user-like/$', views.add_user_like, name='add_user_like'),
    url(r'^goods-filter/$',views.goods_filter, name='goods_filter'),
    url(r'^add-new-tag/$', views.add_new_tag, name='add_new_tag'),
    url(r'^add/$', views.add_good, name='add_good'),
    url(r'^edit/(?P<good_pk>\d+)/$', views.edit_good, name='edit_good'),
    url(r'^delete/(?P<pk>\d+)/$', views.GoodDeleteView.as_view(), name='delete_good'),
    url(r'^upload-good-photo/$', views.upload_good_photo, name='upload_good_photo'),
    url(r'^delete-good-photo/$', views.delete_photo, name='delete_good_photo'),
    url(r'^wishlist/$', views.show_wishlist, name='show_wishlist'),
    url(r'^add-bid/$', views.add_auction_bid, name='add_bid'),
    url(r'^remove-bid/$', views.reject_auction_bid, name='reject_bid'),
    url(r'^disable-good/$', views.set_inactive_good, name='disable-good'),
    url(r'^accept-bid/$', views.accept_bid, name='accept-bid')
]

storesb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from filebrowser.sites import site

from storesb.settings import MEDIA_ROOT, MEDIA_URL

from main.views import index_view
from accounts.views import user_page, cropit


urlpatterns = [
    url(r'^$', index_view, name='index'),
    url(r'^main/', include('main.urls', namespace='main', app_name='main')),
    url(r'^goods/', include('goods.urls', namespace='goods', app_name='goods')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts', app_name='accounts')),
    url(r'^complaints/', include('complaints.urls', namespace='complaints', app_name='complaints')),
    url(r'^chat/', include('chat.urls', namespace='chat', app_name='chat')),
    url(r'^cart/', include('cart.urls', namespace='cart', app_name='cart')),
    url('^pages/', include('pages.urls', namespace='pages', app_name='pages')),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'social-auth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^(?P<user_slug>\w+)/$', user_page, name='user_page'),
    url(r'^cropit$', cropit, name='cropit'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

main/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class SearchForm(forms.Form):
    """
    Simple search form
    """
    query = forms.CharField(widget=forms.TextInput(attrs={'placeholder': _("Search in Sell-n-Buy"), 'autocomplete':"off"}), required=True)

templates/basis.html
<!doctype html>
{% load staticfiles %}
{% load i18n %}
{% load main_tags %}

<html lang="en">
<head>
<meta charset="utf-8">
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% static 'semantic/dist/semantic.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<link href="https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
<script   src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script>
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="/static/semantic/dist/semantic.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block scripts %}{% endblock %}
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>

<body>
    <div id="content" class="ui grid container">
      <a href="#" id="vitrina-icon-bottom">
	         <img src="/static/images/account/vitrina-icon-bottom-n.png">
	         <div class="ui red circular label">1</div>
      </a>
      <a href="#" id="cart-icon-bottom">
	       <img src="/static/images/account/cart-icon-bottom-n.png">
	       <div class="ui red circular label">1</div>
      </a>
            <div class="sixteen wide center aligned column" id="topbar">
                <table>
                    <tr class="olive">
                        <td><a id="search_button" href="javascript:;" class="icon-search"></a></td>
                        <td class="hideon"><a href="#" class="icon-bf"></a></td>
                        <td class="hideon">
                            <a href="{% url 'chat:show_thread_list' %}" class="icon-message"></a>
                            {% if request.user|show_unread_message_count %}<div class="ui red circular label">{{ request.user|show_unread_message_count|safe }}</div>{% endif %}
                        </td>
                        <td class="hideon">
                            <a href="{% url 'goods:show_wishlist' %}" class="icon-wishlist"></a>
                            
                        </td>
                        <td class="hideon">{% if request.user.is_authenticated %}
                            <a href="{{ request.user.profile.get_absolute_url }}" class="icon-main"></a>
                            {% endif %}
                        </td>
                        <td class="hideon">
                            <a href="{% url 'accounts:show_subscriptions' %}" class="icon-users"></a>
                            {% if request.user|show_count_subscriptions %}<div class="ui red circular label">{{ request.user|show_count_subscriptions|safe }}</div>{% endif %}
                        </td>
                        <td class="hideon"><a href="#" class="icon-statistic"></a></td>
                        <td class="hideon"><a href="{% url 'accounts:profile' %}" class="icon-settings"></a></td>
                        <td class="hideon"><a href="#" class="icon-globe"></a></td>
                        <td id="search_input" class="hiden" colspan="8">
                            <form action="/goods/search/" method="get">
                                <input autocomplete="off" class="search olive" id="id_query" name="query" placeholder="Search in S&B" type="text">
                            </form>
                        </td>
                    </tr>
                </table>
            </div>
        {% block content %}{% endblock %}
        <div id="footer" class="sixteen wide center aligned column">
                ПРИСОЕДИНЯЙТЕСЬ К НАМ<br></br>
                <button class="ui circular grey icon button">
                    <i class="vk icon"></i>
                </button>
                <button class="ui circular grey icon button">
                    <i class="facebook f icon"></i>
                </button>
                <button class="ui circular grey icon button">
                    <i class="odnoklassniki icon"></i>
                </button>
                <button class="ui circular grey icon button">
                    <i class="google plus icon"></i>
                </button>
                <button class="ui circular grey icon button">
                    <i class="twitter icon"></i>
                </button>
                <button class="ui circular grey icon button">
                    <i class="pinterest icon"></i>
                </button>
                <br></br>
                SELL-N-BUY. ALL RIGHTS RESERVED. ВСЕ ПРАВА ЗАЩИЩЕНЫ.<br></br>
                2016
            </div>
</body>
</html>

templates/cropit.html
{% extends 'basis.html' %}
{% load i18n %}
{% load staticfiles %}
{% load main_tags %}
{% block title %}{% trans 'Edit your account' %}{% endblock %}
{% block scripts %}
<script src="{% static 'js/cropit.js' %}"></script>
{% endblock %}

{% block content %}
<style>
      .cropit-preview {
        background-color: #f8f8f8;
        background-size: cover;
        border: 1px solid #ccc;
        border-radius: 3px;
        margin-top: 7px;
        width: 250px;
        height: 250px;
      }

      .cropit-preview-image-container {
        cursor: move;
      }

      .image-size-label {
        margin-top: 10px;
      }

      input, .export {
        display: block;
      }

      button {
        margin-top: 10px;
      }
    </style>
  </head>
  <body>
    <div class="image-editor">
      <input type="file" class="cropit-image-input">
      <div class="cropit-preview"></div>
      <div class="image-size-label">
        Resize image
      </div>
      <input type="range" class="cropit-image-zoom-input">
      <button class="rotate-ccw">Rotate counterclockwise</button>
      <button class="rotate-cw">Rotate clockwise</button>

      <button class="export">Export</button>
    </div>

    <script>
      $(function() {
        $('.image-editor').cropit({
          imageState: {
            src: 'http://lorempixel.com/500/400/',
          },
        });

        $('.rotate-cw').click(function() {
          $('.image-editor').cropit('rotateCW');
        });
        $('.rotate-ccw').click(function() {
          $('.image-editor').cropit('rotateCCW');
        });

        $('.export').click(function() {
          var imageData = $('.image-editor').cropit('export');
          window.open(imageData);
        });
      });
    </script>
{% endblock %}