accounts/urls.py
from django.conf.urls import url

from django.contrib.auth import views as django_views

from . import views

urlpatterns = [
    url(r'^registration/$', views.registration_page, name='registration'),
    url(r'^activation/(?P<token>[\w]+)/$', views.activation_view, name='activation'),
    url(r'^password-reset-link/(?P<token>[\w]+)/$', views.activation_view, name='password_reset_link'),
    url(r'^profile/$', views.profile_view, name='profile'),
    url(r'^login/$', django_views.login, name='login'),
    url(r'^logout/$', django_views.logout, name='logout'),
    url(r'^restore/$', views.restore_password, name='restore_password'),
    url(r'^restore-send-email/$', views.restore_send_email, name='restore_send_email'),
    # url(r'^password-reset-link/(?P<token>[\w]+)/$', views.password_reset_link, name='password_reset_link'),
    url(r'^restore-send-sms/$', views.restore_send_sms, name='restore_send_sms'),
    url(r'^password_confirm_code/$', views.password_confirm_code, name='password_confirm_code'),
    # url(r'^password-reset-email/done/$', django_views.password_reset_done, name='password_reset_done'),
    url(r'^logout-then-login/$', django_views.logout_then_login, name='logout_then_login'),
    url(r'^reset-password/$', views.reset_password, name='reset_password'),
    url(r'^add-subscriber/$', views.add_subscriber, name='add_subscriber'),
    url(r'^upload-image/$', views.upload_image, name='upload_image'),
    url(r'^add-review/$', views.add_review, name='add_review'),
    url(r'^show-subscriptions/$', views.show_subscriptions, name='show_subscriptions'),
    url(r'^user-search/$', views.user_search, name='user_search'),
    url(r'^snap-card/$', views.snap_card, name='snap_card')
]

cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^add-to-cart/$', views.add_to_cart, name='add_to_cart'),
    url(r'^cart-detail/$', views.cart_detail, name='cart_detail'),
    url(r'^remove-from-cart/$', views.remove_from_cart, name='remove_from_cart'),
    url(r'^showcase-detail/$', views.show_showcase, name='showcase_detail'),
]

chat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^thread-list/$', views.show_threads_list, name='show_thread_list'),
    url(r'^send-message/$', views.send_message, name='send_message'),
    url(r'^thread/(?P<thread_id>\d+)/$', views.show_thread, name='show_thread'),
    url(r'^send_message_api/$', views.send_message_api, name='send_message_api'),
    url(r'^check_username/$', views.check_username, name='check_username'),
    url(r'^send_message_ajax/$', views.send_message_ajax, name='send_message_ajax'),
]

goods/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^search/$', views.search_view, name='search'),
    url(r'^modal/(?P<good_pk>\d+)/$', views.goods_modal, name='goods_modal'),
    url(r'^good/(?P<good_pk>\d+)/$', views.good_view, name='good_view'),
    url(r'^add-to-wishlist/$', views.add_to_wishlist, name='add_to_wishlist'),
    url(r'^add-user-like/$', views.add_user_like, name='add_user_like'),
    url(r'^goods-filter/$',views.goods_filter, name='goods_filter'),
    url(r'^add-new-tag/$', views.add_new_tag, name='add_new_tag'),
    url(r'^add/$', views.add_good, name='add_good'),
    url(r'^edit/(?P<good_pk>\d+)/$', views.edit_good, name='edit_good'),
    url(r'^delete/(?P<pk>\d+)/$', views.GoodDeleteView.as_view(), name='delete_good'),
    url(r'^upload-good-photo/$', views.upload_good_photo, name='upload_good_photo'),
    url(r'^delete-good-photo/$', views.delete_photo, name='delete_good_photo'),
    url(r'^wishlist/$', views.show_wishlist, name='show_wishlist'),
    url(r'^add-bid/$', views.add_auction_bid, name='add_bid'),
    url(r'^remove-bid/$', views.reject_auction_bid, name='reject_bid'),
    url(r'^disable-good/$', views.set_inactive_good, name='disable-good'),
    url(r'^accept-bid/$', views.accept_bid, name='accept-bid')
]

main/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^calculator/$', views.calculator_view, name='calculator'),
]

pages/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^page/(?P<url>[-\w]+)/$', views.PageDetailView.as_view(), name='page_view'),
]

storesb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from filebrowser.sites import site

from storesb.settings import MEDIA_ROOT, MEDIA_URL

from main.views import index_view
from accounts.views import user_page, cropit


urlpatterns = [
    url(r'^$', index_view, name='index'),
    url(r'^main/', include('main.urls', namespace='main', app_name='main')),
    url(r'^goods/', include('goods.urls', namespace='goods', app_name='goods')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts', app_name='accounts')),
    url(r'^complaints/', include('complaints.urls', namespace='complaints', app_name='complaints')),
    url(r'^chat/', include('chat.urls', namespace='chat', app_name='chat')),
    url(r'^cart/', include('cart.urls', namespace='cart', app_name='cart')),
    url('^pages/', include('pages.urls', namespace='pages', app_name='pages')),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'social-auth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^(?P<user_slug>\w+)/$', user_page, name='user_page'),
    url(r'^cropit$', cropit, name='cropit'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.


class BaseModel(models.Model):
    """
    Model to auto add updated/created fields to models
    """
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

main/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class SearchForm(forms.Form):
    """
    Simple search form
    """
    query = forms.CharField(widget=forms.TextInput(attrs={'placeholder': _("Search in Sell-n-Buy"), 'autocomplete':"off"}), required=True)

main/views.py
from django.shortcuts import render

from .forms import SearchForm
from accounts.functions import define_theme


# Create your views here.


def index_view(request):
    """
    Index view (render index.html). SHow search form. Randomize theme.
    :param request: HttpRequest
    :return: HttpResponse
    """
    form = SearchForm()
    theme_id = define_theme(request)
    return render(request, "index.html", {"theme_id": theme_id, 'form': form})


def calculator_view(request):
    """
    Calculator view. Show calculator page
    :param request: HttpRequest
    :return: HttpResponse
    """
    form = SearchForm()
    return render(request, "calculator.html", {'form': form})

main/templates/base.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block scripts %}{% endblock %}
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

main/templates/calculator.html
{% load staticfiles %}
{% load i18n %}
{% load cart_tags %}
{% load main_tags %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% trans 'Calculator' %}</title>
    <link rel="stylesheet" href="{% static 'css/calculator/Mstyle.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'css/calculator/modal_styles.css' %}" type="text/css" media="all">
    <script type="text/javascript" src="{% static 'js/calculator/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/calculator/calc.js' %}"></script>
    <script src="http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script>
    <!--[if IE]>
        <link rel="stylesheet" href="{% static 'css/calculator/styleIE.css' %}" type="text/css" media="all">
        <script type="text/javascript" src="{% static 'js/calculator/html5.js' %}"></script>
    <![endif]-->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" type="text/css">
    <script type="text/javascript">
        $(function() {
            $(window).scroll(function() {
                if($(this).scrollTop() != 0) {
                    $('#up').fadeIn();
                } else {
                    $('#up').fadeOut();
                }
            });
            $('#up').click(function() {
                $('body,html').animate({scrollTop:0},800);
            });
        });

        $(document).ready(function () {
            // Get CSRF cookie protection
            var csrftoken = $.cookie('csrftoken');
            function csrfSafeMethod (method) {
                // These HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if(!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        // Set X-CSRFToken HTTP Header
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });


            // Modal window
            var card_link = document.getElementById('snap_card');
            card_link.onclick = function (e) {
                e.preventDefault();
                modal.style.display = "block";
            }
            var modal = document.getElementById('card-modal');
            var span = document.getElementsByClassName("close")[0];
            span.onclick = function() {
                modal.style.display = "none";
            }
            window.onclick = function(event) {
                if (event.target == modal) {
                    modal.style.display = "none";
                }
            }
        });
    </script>
</head>
<body>
    <div id="wrapper" class="green">
        <div id="up"></div>
        {% include 'cart_showcase_block.html' %}
        <header class="black">
            {% if request.user.is_authenticated %}
                <ul>
                    <li class="search-modal"><div ></div></li>
                    <li>
                        <a href="{% url 'accounts:show_subscriptions' %}"></a>
                        {{ request.user|show_count_subscriptions|safe }}
                    </li>
                    <li>
                        <a href="#"></a><span>258</span>
                    </li>
                    <li>
                        <a href="{% url 'chat:show_thread_list' %}"></a>
                        {{ request.user|show_unread_message_count|safe }}
                    </li>
                    <li>
                        <a href="{% url 'goods:show_wishlist' %}"></a>
                        {{ request.user|show_count_goods_in_wishlist|safe }}
                    </li>
                    <li>
                        <a href="{{ request.user.profile.get_absolute_url }}"></a>
                    </li>
                    <li>
                        <a href="{% url 'main:calculator' %}"></a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:user_search' %}"></a>
                    </li>
                    <li>
                        <a href="#"></a>
                        <span>258</span>
                    </li>
                    <li>
                        <a href="{% url 'accounts:profile' %}"></a>
                    </li>
                    <li>
                        <div>
                            <a href="{% url 'accounts:logout' %}"></a>
                        </div>
                    </li>
                </ul>
            {% else %}
                <div class="sign-up">
                    <div>
                        <span>
                            <a href="{% url 'accounts:login' %}" class="sign-up-link">{% trans 'SIGN UP' %}</a>
                        </span>
                    </div>
                </div>
            {% endif %}
		    <div class="clear"></div>
	    </header>
	    <div class="search-box">
			<img class="img-search" src="{% static 'images/calculator/search-green-icon_03.png' %}">
            <form action="{% url 'goods:search' %}" method="get">
                {{ form.query|add_class_to_formfield:"search" }}
            </form>
		</div>
        <div id="wrapper-calc">
            <div id="headerbtn">
{#                <div id="pursebtn" class="hbtn">{% trans 'Purse' %}</div>#}
                <div id="calcbtn" class="hbtn bbtn-active">{% trans 'Calculator' %}</div>
			<div class="clear"></div>
		</div>
		<div class="calc-boxes-wrapper">
			<div id="leftcalcbox">
				<div class="calculator-panel">
					<h3>{% trans 'Select the type of deal' %}</h3>
					<div id="bbtn1" class="bbtn bbtn-active">{% trans 'Buy/Sell' %}</div>
					<div id="bbtn2" class="bbtn">{% trans 'Acution' %}</div>
					<div id="bbtn3" class="bbtn">{% trans 'Sale' %}</div>
					<div id="ibox1"></div>
					<h3>{% trans 'Enter a currency and the price of goods' %}</h3>
					<div id="calc1">
						<!-- <div id="currency1"></div> -->
						<div class="iblock" id="m0">
							<p>{% trans 'The price of the product' %}</p>
							<input type="text" class="nonnumb iptclear" id="firstSale" value="0">
							<div class="clear"></div>
						</div>
					</div>
					<div id="calc2" style="display:none;">
						<!-- <div id="currency"></div> -->
						<div class="iblock">
							<p>{% trans 'Starting price' %}</p>
							<input type="text" class="nonnumb iptclear" id="secondSale1" value="0">
						</div>
						<div class="iblock">
							<p>{% trans 'Reserve price' %}</p>
							<input type="text" class="nonnumb iptclear" id="secondSale2" value="0">
						</div>
						<div class="iblock">
							<p>{% trans 'Final price' %}</p>
							<input type="text" class="nonnumb iptclear" id="secondSale3" value="0">
						</div>
					</div>
					<div id="calc3" style="display:none;">
						<!-- <div id="currency2"></div> -->
						<div class="iblock">
							<p>{% trans 'Starting price' %}</p>
							<input type="text" class="nonnumb iptclear" id="thirdSale1" value="0">
						</div>
						<div class="iblock" style="float:right !important">
							<p>{% trans 'Price with discount' %}</p>
							<input type="text" class="nonnumb iptclear" id="thirdSale2" value="0">
						</div>
					</div>
					<div class="clear"></div>
					<div id="ibox1"></div>
					<h3>{% trans 'Enter the postage' %}</h3>
					<input type="text" id="delivery" class="nonnumb iptclear" value="0">
				</div>
			</div>
			<div id="rightcalcbox">
				<h3>{% trans 'Your final price' %}</h3>
				<p>{% trans 'Total cost' %}</p>
				<span id="main-sale">0</span>
				<p>{% trans 'Commission' %} <span>Sell-n-buy</span></p>
				<span id="commission">0</span>
				<h4>{% trans 'Total' %}:</h4>
				<div id="return-block">
					<h3>{% trans 'Your profit' %}</h3>
					<span id="return-sale">0</span>
					<input type="button" value="{% trans 'Calculate' %}" class="rbtn" id="btnStart1">
					<input type="button" value="{% trans 'Calculate' %}" class="rbtn" id="btnStart2" style="display:none;">
					<input type="button" value="{% trans 'Calculate' %}" class="rbtn" id="btnStart3" style="display:none;">
					<input type="button" value="{% trans 'Reset' %}" class="rbtn" id="resetbtn">
				</div>
			</div>
			<div class="clear"></div>
		</div>
{#            TODO: commented for future use #}
{#		<div class="wallet-panel">#}
{#            <div class="wallet clearfix">#}
{#                <h2 class="wallet-headline cash">CASH</h2>#}
{#                <div class="act-replenish">#}
{#                    <div class="replenish">#}
{#                        <a href="#">{% trans 'Refill' %}</a>#}
{#                    </div>#}
{#                    <div class="withdraw">#}
{#                        <a href="#">{% trans 'Withdraw' %}</a>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="total-eliminate">#}
{#                    0#}
{#                </div>#}
{#                <a href="#" class="binding-card main-cta" id="snap_card">{% trans 'Snap a card' %}</a>#}
{#                <div class="binding-card-words">#}
{#                    {% blocktrans %}#}
{#                        <p>Tie your bank card,</p>#}
{#                        <p>to securely pay for purchases with it,</p>#}
{#                        <p>even when there is no money purse.</p>#}
{#                    {% endblocktrans %}#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
	</div>
</div>
<!-- The Card modal -->
    <div id="card-modal" class="card-modal">
        <div class="card-modal-content">
            <div class="card-modal-header">
                <h4>{% trans 'Snap a card' %}</h4>
                <span class="close">×</span>
            </div>
            <div class="card-modal-body">
                <h4>{% trans 'Enter your card data' %}</h4>
                <label for="id_card">{% trans 'Enter card number' %}</label>
                <br>
                <input type="number" name="card" id="id_card">
                <br>
                <label for="id_month">{% trans 'Enter card month' %}</label>
                <br>
                <input type="number" name="month" id="id_month">
                <br>
                <label for="id_year">{% trans 'Enter card year' %}</label>
                <br>
                <input type="number" name="year" id="id_year">
                <button type="submit" class="add-card-button" onclick="snapCard()">
                    {% trans 'Snap a card' %}
                </button>
            </div>
        </div>
    </div>
<footer>
	<h3>{% trans 'Join us' %}</h3>
	<ul id="social">
		<li><a href="#"></a></li>
		<li><a href="#"></a></li>
		<li><a href="#"></a></li>
		<li><a href="#"></a></li>
		<li><a href="#"></a></li>
		<li><a href="#"></a></li>
	</ul>
	<div id="copyright">Sell-n-buy. all rigths reserved. все права защищены<br> arton</div>
</footer>
<script>
	$('#pursebtn').click(function(){
		$('.wallet-panel').show();
		$('#headerbtn div').removeClass('bbtn-active');
		$(this).addClass('bbtn-active');
		$('.calc-boxes-wrapper').hide();
	});
	$('#calcbtn').click(function(){
		$('.wallet-panel').hide();
		$('#headerbtn div').removeClass('bbtn-active');
		$(this).addClass('bbtn-active');
		$('.calc-boxes-wrapper').show();
	});
	$('.search-modal').click(function (){
		$('.search-box').show();
		$(this).parents('header').hide();
	});
	$('.img-search').click(function (){
		$(this).parent().hide();
		$('header').show();
	});
	$('input[class="search"]').keypress(function (e) {
	    var key = e.which;
        if(key == 13)  // the enter key code
        {
            $(this).parent().hide();
            $('header').show();
        }
	});
</script>
</body>
</html>

main/templates/cart_showcase_block.html
{% load staticfiles %}
{% load cart_tags %}
<a href="{% url 'cart:showcase_detail' %}" id="vitrina-icon-bottom">
    <span>{% show_showcase_count %}</span>
    <img src="{% static 'images/wishlist/vitrina-icon-bottom-n.png' %}">
</a>
<a href="{% url 'cart:cart_detail' %}" id="cart-icon-bottom">
    <span>{% show_carts_count %}</span>
    <img src="{% static 'images/wishlist/cart-icon-bottom-n.png' %}">
</a>

main/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if messages %}
    {% for message in messages %}
        {{ message }}
    {% endfor %}
{% endif %}
</body>
</html>

main/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load main_tags %}
{% block title %}{% trans "Welcome" %}{% endblock %}
{% block scripts%}
    <link rel="stylesheet" href="{% static 'css/index/Mstyle.css' %}" type="text/css" media="all">
    <script type="text/javascript" src="{% static 'js/index/jquery.min.js' %}"></script>
    <!--[if IE]>
	    <link rel="stylesheet" href="{% static 'css/index/styleIE.css' %}" type="text/css" media="all">
	    <script type="text/javascript" src="{% static 'js/index/html5.js' %}"></script>
	<![endif]-->
{% endblock %}
{% block content %}
    {% if theme_id == 0 %}
        <div id="wrapper" class="green">
    {% else %}
	    <div id="wrapper" class="orange">
    {% endif %}
		<div id="logo">
			<form action="{% url 'goods:search' %}" method="get">
                {{ form.query|add_class_to_formfield:"search" }}
			</form>
		</div>
		<nav id="main-menu">
			<ul>
				<li><a href="{% url 'pages:page_view' 'your-business' %}">{% trans 'For your business' %}</a></li>
				<li><a href="{% url 'pages:page_view' 'advertising' %}">{% trans 'Advertising' %}</a></li>
				<li>
{#                    <a href="#">{% trans 'Language' %}</a>#}
                    <form action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input name="next" type="hidden" value="{{ redirect_to }}" />
                        <select name="language" class="{% if theme_id == 0 %}select-green{% else %}select-orange{% endif %}" onchange="this.form.submit()">
                            {% get_language_info_list for LANGUAGES as languages %}
                            {% for language in languages %}
                                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                                    {{ language.name_local }} ({{ language.code }})
                                </option>
                            {% endfor %}
                        </select>
                    </form>
                </li>
				<li><a href="{% url 'pages:page_view' 'rules' %}">{% trans 'Rules' %}</a></li>
				<li><a href="{% url 'pages:page_view' 'terms-and-privacy' %}">{% trans 'Terms and Privacy' %}</a></li>
			</ul>
		</nav>
	</div>
{% endblock %}

main/templates/main_menu.html
{% load staticfiles %}
{% load main_tags %}
{% load chat_tags %}
<ul>
    <li class="green-photos">
        <div class="search-modal">
            <img src="{% static 'images/user_search/search-green-icon_03.png' %}">
        </div>
    </li>
    <li class="green-photos">
        <a href="{% url 'accounts:show_subscriptions' %}">
            <img src="{% static 'images/user_search/2-green-menu.png' %}">
        </a>
        {{ request.user|show_count_subscriptions|safe }}
    </li>
    <li class="green-photos">
        <a href="#">
            <img src="{% static 'images/user_search/3-green-menu.png' %}">
        </a>
        <span>258</span>
    </li>
    <li class="green-photos">
        <a href="{% url 'chat:show_thread_list' %}">
            <img class="image-correct" src="{% static 'images/user_search/4-green-menu.png' %}">
        </a>
        {{ request.user|show_unread_message_count|safe }}
    </li>
    <li class="green-photos">
        <a href="{% url 'goods:show_wishlist' %}">
            <img src="{% static 'images/user_search/5-green-menu.png' %}">
        </a>
        {{ request.user|show_count_goods_in_wishlist|safe }}
    </li>
    <li class="green-photos central-photo">
        <a href="{{ request.user.profile.get_absolute_url }}">
            <img src="{% static 'images/user_search/avatar-green-menu.png' %}">
        </a>
    </li>
    <li class="green-photos">
        <a href="{% url 'main:calculator' %}">
            <img src="{% static 'images/user_search/6-green-menu.png' %}">
        </a>
    </li>
    <li class="green-photos">
        <a href="{% url 'accounts:user_search' %}">
            <img src="{% static 'images/user_search/7-green-menu.png' %}">
        </a>
    </li>
    <li class="green-photos">
        <a href="#">
            <img src="{% static 'images/user_search/8-green-menu.png' %}">
        </a>
        <span>258</span>
    </li>
    <li class="green-photos">
        <a href="{% url 'accounts:profile' %}">
            <img src="{% static 'images/user_search/9-green-menu.png' %}">
        </a>
    </li>
    <li class="green-photos">
        <a href="{% url 'accounts:logout' %}">
            <div>
                <img src="{% static 'images/user_search/world-green-icon_03.png' %}">
            </div>
        </a>
    </li>
</ul>

main/templates/sign_in.html
{% load i18n %}
<div class="sign-up">
    <div>
        <span>
            <a href="{% url 'accounts:login' %}" class="sign-up-link">{% trans 'SIGN UP' %}</a>
        </span>
    </div>
</div>

main/templates/social_links.html
{% load i18n %}
{% load main_tags %}
<h3>{% trans 'Join us' %}</h3>
	<ul id="social">
		<li><a href="{{ site_root|social_share:VK }}"></a></li>
		<li><a href="{{ site_root|social_share:FACEBOOK }}"></a></li>
		<li><a href="#"></a></li>
		<li><a href="#"></a></li>
		<li><a href="#"></a></li>
		<li><a href="{{ site_root|social_share:PINTEREST }}"></a></li>
	</ul>
<div id="copyright">Sell-n-buy. all rigths reserved. все права защищены<br> arton</div>